---
title: "Fission-Fusion test file"
author: "Natalia Fedorova"
date: "8/1/2018"
output: html_document
---

```{r setup} 
options(width = 10000)
```

Initialize function
```{r}

fig3_debugger <- function(bands = list(group_size = c(2, 2), fitness = c(4, 8)), model = 2, model_groupsize = NA){

  payoff_default <- 10
  threshold <- 3
  i <- 1
  
  #Fission fusion options:
  #no change
  nc_1 <- all(c(bands$group_size[i] ==1, bands$group_size[model] ==1, bands$fitness[i] >= bands$fitness[model])) 
  nc_2 <- all(c(bands$group_size[i] ==1, is.null(model_groupsize) == TRUE )) 
  nc_3 <- all(c(bands$group_size[i] >1, bands$group_size[model] >1, bands$fitness[i] >= bands$fitness[model], bands$fitness[i] > payoff_default - threshold))
  nc_4 <- all(c(bands$group_size[i] >1, bands$group_size[model] ==1, bands$fitness[i] >= bands$fitness[model], bands$fitness[i] > payoff_default - threshold))
  
  #fission
  fis_1 <- all(c(bands$group_size[i] >1, bands$group_size[model] >1, bands$fitness[i] <=payoff_default - threshold, bands$fitness[model] <= payoff_default - threshold))
  fis_2 <- all(c(bands$group_size[i] >1, bands$group_size[model] >1, bands$fitness[i] >= bands$fitness[model], bands$fitness[i] <= payoff_default - threshold))
  fis_3 <- all(c(bands$group_size[i] >1, bands$group_size[model] ==1, bands$fitness[i] >= bands$fitness[model], bands$fitness[i] <= payoff_default - threshold))
  fis_4 <- all(c(bands$group_size[i] >1, bands$group_size[model] ==1, bands$fitness[i] <= bands$fitness[model] - threshold))
  fis_5 <- all(c(bands$group_size[i] >1, bands$group_size[model] ==1, bands$fitness[i] <= payoff_default - threshold))
  fis_6 <- all(c(bands$group_size[i] >1, is.null(model_groupsize) == TRUE , bands$fitness[i] <= payoff_default - threshold))
  
  #fusion
  fus_1 <- all(c(bands$group_size[i] ==1, bands$group_size[model] ==1, bands$fitness[i] < payoff_default, bands$fitness[model] < payoff_default))
  
  #fusion, join group
  fusg_1 <- all(c(bands$group_size[i] ==1, bands$group_size[model] >1, bands$fitness[i] <= bands$fitness[model] - threshold))
  
  #migration
  mig_1 <- all(c(bands$group_size[i] >1, bands$group_size[model] >1, bands$fitness[i] <= payoff_default - threshold, bands$fitness[model] > payoff_default - threshold))
  mig_2 <- all(c(bands$group_size[i] >1, bands$group_size[model] >1, bands$fitness[i] <= bands$fitness[model] - threshold, bands$fitness[model] > payoff_default - threshold))

  conds <- c("nc_1_1", "nc_2_2", "nc_3_3", "nc_4_4", "fis_1_5", "fis_2_6", "fis_3_7", "fis_4_8", "fis_5_9", "fis_6_10", "fus_1_11", "fusg_1_12", "mig_1_13", "mig_2_14")
  dat <- c(nc_1, nc_2, nc_3, nc_4, fis_1, fis_2, fis_3, fis_4, fis_5, fis_6, fus_1, fusg_1, mig_1, mig_2)
  
  out <- list(
    conds = conds,
    dat = dat,
    dat_sum = sum(dat, na.rm = TRUE)
  )
  
  return(out)
  
}

```

##No change

nc_1: gi = 1, gw = 1, fi >= fw
```{r}
conds <- c("nc_1_1", "nc_2_2", "nc_3_3", "nc_4_4", "fis_1_5", "fis_2_6", "fis_3_7", "fis_4_8", "fis_5_9", "fis_6_10", "fus_1_11", "fusg_1_12", "mig_1_13", "mig_2_14")
bands <- list()
bands$group_size <- c(1,1)
bands$fitness <- c(10,8)
print(conds)
fig3_debugger(bands = bands)

```

nc_2: gi = 1, gw = NULL
```{r}
bands$group_size <- c(1,1)

#when model is set to NA, (as opposed to integer(0), we get the right TRUE, because indexing with model that doesn't exist gives us NA rather than TRUE (because of how all() works))
model <- NA

model_groupsize <- NULL

fig3_debugger(bands = bands, model = model, model_groupsize = model_groupsize)

```

nc_3: gi > 1, gw > 1, fi >= fw, fi > default - c
```{r}
bands$group_size <- c(2,2)
bands$fitness <- c(10,8)
fig3_debugger(bands = bands)

```

nc_4: gi > 1, gw = 1, fi >= fw, fi > default - c
```{r}
bands$group_size <- c(2,1)
bands$fitness <- c(10,8)
fig3_debugger(bands = bands)

```

##Fission

fis_1: gi > 1, gw > 1, fi <= default - c, fw <= default - c
```{r}
bands$group_size <- c(2,2)
bands$fitness <- c(6,6)
fig3_debugger(bands = bands)

```

fis_2: gi > 1, gw > 1, fi >= fw, fi <= default - c
```{r}
bands$group_size <- c(2,2)
bands$fitness <- c(6,5)
fig3_debugger(bands = bands)

```

The above two seem to be indistinguishable because the second clause doesn't have an fi to fw comparison - and that's actually the only difference between them


fis_3: gi > 1, gw = 1, fi >= fw, fi <= default -c
```{r}
bands$group_size <- c(2,1)
bands$fitness <- c(6,5)
fig3_debugger(bands = bands)

```

fis_4: gi > 1, gw = 1, fi <= fw - c
```{r}
bands$group_size <- c(2,1)
bands$fitness <- c(10,14)
fig3_debugger(bands = bands)

```

fis_5: gi > 1, gw = 1, fi <= default - c
```{r}
bands$group_size <- c(2,1)
bands$fitness <- c(6,10)
fig3_debugger(bands = bands)

```

The same seems to be true of fis_3 and fis_5, which are the same apart from the comparative fi and fw clause

fis_6: gi > 1, gw = NULL, fi <= default - c
```{r}
bands$group_size <- c(2,1)
bands$fitness <- c(6,10)

model <- NA

model_groupsize <- NULL

fig3_debugger(bands = bands, model = model, model_groupsize = model_groupsize)

```


##Fusion

fus_1: gi = 1, gw = 1, fi < default, fw < default
```{r}
bands$group_size <- c(1,1)
bands$fitness <- c(9,9)
fig3_debugger(bands = bands)

```

The above fusion cannot be determined from nc_1 because it does not take into account the fi fw relationship

##Fusion join group

fusg_1: gi = 1, gw > 1, fi <= fw - c
```{r}
bands$group_size <- c(1,2)
bands$fitness <- c(10,14)
fig3_debugger(bands = bands)

```

##Migration

mig_1: gi > 1, gw > 1, fi <= default - c, fw > default - c, 
```{r}
bands <- list()
bands$group_size <- c(2,2)
bands$fitness <- c(6,8)
fig3_debugger(bands = bands)

```


mig_2: gi > 1, gw > 1, fw > default - c, fi <= fw - c
```{r}
bands$group_size <- c(2,2)
bands$fitness <- c(4,8)
fig3_debugger(bands = bands)

```

Same with these last two, only one of them has a fi and fw comparison 


```{r, eval = FALSE}

if(nc_1 == TRUE | nc_2 == TRUE | nc_3 == TRUE | nc_4 == TRUE ){
  #do nothing
}else if(fis_1 == TRUE | fis_2 == TRUE | fis_3 == TRUE | fis_4 == TRUE | fis_5 == TRUE | fis_6 == TRUE){
  #fission - move to empty patch in neighbourhood
  #FIX ME - how I do this depends on what is done above with the neighbour index
  #find empty patches and randomly select one to move to 
  bands$patch_id[i] <- sample(neigh_patchs[which(is.na(set))], 1)
}else if(fus_1 == TRUE){
  #fusion - join together to make a group
  #FIX ME - need to figure out how to then count this as a move for the model as well
  #find empty patches and randomly select one, assign to new variable new_patch
  new_patch <- sample(neigh_patchs[which(is.na(set))], 1)
  
  #assign new patch as the patch for both the agent i and the model
  bands$patch_id[i] <- new_patch
  bands$patch_id[model] <- new_patch
}else if(fusg_1 == TRUE | mig_1 == TRUE | mig_2 == TRUE){
  #fusion - join model's group after being alone
  #migrate to models group
  bands$patch_id[i] <- bands$patch_id[model]
}

```